//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int ArticleID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateOfOrder { get; set; }
        public System.DateTime DateOfArrival { get; set; }
        public int PickUpPointID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ReceiveCode { get; set; }
        public int StatusID { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
