//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string Article { get; set; }
        public int ProductNameID { get; set; }
        public int UnitID { get; set; }
        public decimal Price { get; set; }
        public int MaxSale { get; set; }
        public int ManufacturerID { get; set; }
        public int DealerID { get; set; }
        public int ProductCategoryID { get; set; }
        public int Sale { get; set; }
        public int QuantityInStock { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Units Units { get; set; }
    }
}
